language: c

os:
  - linux

sudo: required
dist: trusty

compiler:
  - gcc

install:
  - 'sh ./.install-cross-mint.sh'
  - 'sudo apt-get install -ym mtools'

script:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'make ce_main_app ONPC=yes V=1'
  - 'make atari_progs'
  - 'make update'
